### ISSUE TITLE
Wrong number range output after inputting an invalid minute value

### ISSUE THREAD

**Issue by hmagan** [tsar-boomba/Isaiah-Utils#3]
I was trying to enjoy this application but I noticed a bug; if you input an invalid number to the question "What minute will the rotation start at? (0-59)", it returns "Please input a number between 1 and 12" instead of 0 and 59 (pic related). Please fix 😭😭😭😭😭

![Screenshot from 2021-06-18 08-33-30](https://user-images.githubusercontent.com/70351743/122561887-6061ac00-d010-11eb-9d15-c03e9c32e16c.png)

**Comment by tsar-boomba** [comment]
![Screenshot_200](https://user-images.githubusercontent.com/77396670/122562568-38267d00-d011-11eb-87aa-307bbb832d33.png)
fixed!

**Comment by hmagan** [comment]
Thanks!
